/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/problems/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Problems
         * @description Get list of all problems ordered by sequence number.
         *
         *     Returns basic problem info without test cases or language details.
         */
        get: operations["get_problems_api_problems__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/problems/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Problem
         * @description Get detailed problem information including test cases and language configs.
         *
         *     Returns first 3 test cases by sequence order.
         *     Also returns user's saved code if it exists.
         */
        get: operations["get_problem_api_problems__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/problems/languages/supported": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Languages
         * @description Get list of supported programming languages for code execution.
         *
         *     Returns languages that have wrapper generators implemented.
         */
        get: operations["get_languages_api_problems_languages_supported_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Code
         * @description Run code against first 3 test cases or custom inputs.
         *
         *     This is the "Run Code" button - shows first 3 test cases by sequence order,
         *     or runs against custom inputs if provided.
         */
        post: operations["run_code_api_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Code
         * @description Submit code against ALL test cases.
         *
         *     This is the "Submit" button - runs all tests and updates user progress.
         */
        post: operations["submit_code_api_submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rate-submission": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rate Submission
         * @description Rate the difficulty of a successfully solved problem.
         *
         *     After a successful submission, the user rates how difficult it felt:
         *     - "again": Reset to 1 day, decrease ease factor
         *     - "hard": Slow interval growth, decrease ease slightly
         *     - "good": Normal interval growth using ease factor
         *     - "mastered": Immediately mark as mastered, exit rotation
         *
         *     This implements the Anki SM-2 spaced repetition algorithm.
         */
        post: operations["rate_submission_api_rate_submission_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Today
         * @description Get today's session: up to 2 review problems + 1 new problem.
         *
         *     Returns problems due for review plus the next unsolved problem.
         */
        get: operations["get_today_api_today_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Progress
         * @description Get user's overall progress across all Blind 75 problems.
         *
         *     Returns all problems with user progress, plus summary counts.
         */
        get: operations["get_progress_api_progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mastered": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Mastered
         * @description Get list of all mastered problems.
         *
         *     Returns problems with mastery info and last submission, sorted by most recently solved.
         */
        get: operations["get_mastered_api_mastered_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mastered/{problem_id}/show-again": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Show Again
         * @description Re-add a mastered problem to review rotation.
         *
         *     Sets the problem to be reviewed again starting today.
         */
        post: operations["show_again_api_mastered__problem_id__show_again_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submissions/{problem_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Submissions
         * @description Get submission history for a specific problem.
         *
         *     Returns all submissions by the user for this problem, ordered by most recent first.
         */
        get: operations["get_submissions_api_submissions__problem_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/code/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save Code
         * @description Save user's code for a problem.
         *
         *     Upserts into user_code table - creates new record or updates existing.
         *     Called by frontend on debounced code changes (every 500ms after typing stops).
         */
        post: operations["save_code_api_code_save_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/code/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Code
         * @description Reset user's code to starter code by deleting their saved code record.
         *
         *     After this, fetching the problem will return starter_code since no user_code exists.
         */
        post: operations["reset_code_api_code_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/code/load-submission": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Load Submission Code
         * @description Load code from a past submission into the editor.
         *
         *     Updates user_code with the submission's code so it appears in the editor.
         */
        post: operations["load_submission_code_api_code_load_submission_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Models
         * @description Get list of available LLM models.
         *
         *     Returns models that have valid API keys configured.
         *     First model in list is the default.
         */
        get: operations["list_models_api_chat_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Chat Session
         * @description Create a new chat session for a problem.
         *
         *     The session will use the default model if none is specified.
         */
        post: operations["create_chat_session_api_chat_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/sessions/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions
         * @description Get all chat sessions for a problem.
         *
         *     Returns sessions ordered by most recent first.
         */
        get: operations["list_sessions_api_chat_sessions__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/session/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Chat Session
         * @description Get a chat session with all messages.
         *
         *     Only returns session if it belongs to the authenticated user.
         */
        get: operations["get_chat_session_api_chat_session__session_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Chat Session
         * @description Delete a chat session (soft delete).
         *
         *     Sets is_active=False instead of actually deleting.
         */
        delete: operations["delete_chat_session_api_chat_session__session_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Chat Session
         * @description Update a chat session.
         *
         *     Can update title, mode, model, or active status.
         */
        patch: operations["update_chat_session_api_chat_session__session_id__patch"];
        trace?: never;
    };
    "/api/chat/session/{session_id}/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Message Stream
         * @description Send a message and stream AI response in a single request.
         *
         *     This endpoint:
         *     1. Saves the user message to the database
         *     2. Streams the AI response using Server-Sent Events format
         *     3. Saves the complete AI response to the database
         *
         *     The response is a streaming response with SSE format:
         *     - data: {"type": "chunk", "content": "..."}
         *     - data: {"type": "done", "message_id": "..."}
         *     - data: {"type": "error", "error": "..."}
         */
        post: operations["send_message_stream_api_chat_session__session_id__message_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Root endpoint - returns application info.
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ChatMessageSchema
         * @description Chat message schema.
         */
        ChatMessageSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            role: components["schemas"]["MessageRole"];
            /** Content */
            content: string;
            /** Code Snapshot */
            code_snapshot?: string | null;
            /** Test Results Snapshot */
            test_results_snapshot?: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ChatMode
         * @description Chat assistant modes.
         * @enum {string}
         */
        ChatMode: "socratic" | "direct";
        /**
         * ChatSessionSchema
         * @description Chat session schema (without messages).
         */
        ChatSessionSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** User Id */
            user_id: string;
            /**
             * Problem Id
             * Format: uuid
             */
            problem_id: string;
            /** Title */
            title: string | null;
            mode: components["schemas"]["ChatMode"];
            /** Model */
            model: string | null;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ChatSessionWithMessagesSchema
         * @description Chat session with all messages.
         */
        ChatSessionWithMessagesSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** User Id */
            user_id: string;
            /**
             * Problem Id
             * Format: uuid
             */
            problem_id: string;
            /** Title */
            title: string | null;
            mode: components["schemas"]["ChatMode"];
            /** Model */
            model: string | null;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Messages */
            messages: components["schemas"]["ChatMessageSchema"][];
        };
        /**
         * CreateSessionRequest
         * @description Request to create a new chat session.
         */
        CreateSessionRequest: {
            /** Problem Slug */
            problem_slug: string;
            /** @default socratic */
            mode: components["schemas"]["ChatMode"];
            /**
             * Model
             * @description LLM model (uses default if None)
             */
            model?: string | null;
            /**
             * Title
             * @description Optional session title
             */
            title?: string | null;
        };
        /**
         * Difficulty
         * @description Problem difficulty levels.
         * @enum {string}
         */
        Difficulty: "easy" | "medium" | "hard";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Language
         * @description Supported programming languages.
         * @enum {string}
         */
        Language: "python" | "javascript";
        /**
         * LoadSubmissionRequest
         * @description Request body for loading code from a submission.
         */
        LoadSubmissionRequest: {
            /** Problem Slug */
            problem_slug: string;
            /** Code */
            code: string;
            /**
             * Language
             * @default python
             */
            language: string;
        };
        /**
         * MasteredProblemSchema
         * @description Schema for mastered problems list (nested structure for frontend).
         */
        MasteredProblemSchema: {
            problem: components["schemas"]["ProblemBasicSchema"];
            user_progress: components["schemas"]["UserProgressBasicSchema"];
            last_submission: components["schemas"]["SubmissionBasicSchema"] | null;
        };
        /**
         * MasteredProblemsResponse
         * @description Response wrapper for mastered problems list.
         */
        MasteredProblemsResponse: {
            /** Mastered Problems */
            mastered_problems: components["schemas"]["MasteredProblemSchema"][];
        };
        /**
         * MessageRole
         * @description Chat message roles.
         * @enum {string}
         */
        MessageRole: "user" | "assistant" | "system";
        /**
         * ModelInfo
         * @description Available model information.
         */
        ModelInfo: {
            /** Name */
            name: string;
            /** Display Name */
            display_name: string;
            /** Is Default */
            is_default: boolean;
        };
        /**
         * ProblemBasicSchema
         * @description Basic problem info for progress list.
         */
        ProblemBasicSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Slug */
            slug: string;
            difficulty: components["schemas"]["Difficulty"];
            /** Pattern */
            pattern: string[];
            /** Sequence Number */
            sequence_number: number;
        };
        /**
         * ProblemDetailSchema
         * @description Detailed problem schema with all related data.
         *
         *     Includes test cases (visible only), language configs, etc.
         */
        ProblemDetailSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Slug */
            slug: string;
            /** Description */
            description: string;
            difficulty: components["schemas"]["Difficulty"];
            /** Pattern */
            pattern: string[];
            /** Sequence Number */
            sequence_number: number;
            /** Constraints */
            constraints: string[];
            /** Examples */
            examples: components["schemas"]["ProblemExampleSchema"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Languages */
            languages: components["schemas"]["ProblemLanguageSchema"][];
            /** Test Cases */
            test_cases: components["schemas"]["TestCaseSchema"][];
            /** User Code */
            user_code?: string | null;
            /**
             * Is Due
             * @default false
             */
            is_due: boolean;
        };
        /**
         * ProblemExampleSchema
         * @description Example schema for problem examples.
         */
        ProblemExampleSchema: {
            /** Input */
            input: string;
            /** Output */
            output: string;
            /** Explanation */
            explanation?: string | null;
        };
        /**
         * ProblemLanguageSchema
         * @description Problem language-specific data.
         */
        ProblemLanguageSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            language: components["schemas"]["Language"];
            /** Starter Code */
            starter_code: string;
            /** Reference Solution */
            reference_solution: string;
            /** Function Signature */
            function_signature: {
                [key: string]: unknown;
            };
        };
        /**
         * ProblemProgressSchema
         * @description Problem with user's progress info.
         */
        ProblemProgressSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Slug */
            slug: string;
            difficulty: components["schemas"]["Difficulty"];
            /** Pattern */
            pattern: string[];
            /** Sequence Number */
            sequence_number: number;
            /**
             * Times Solved
             * @default 0
             */
            times_solved: number;
            /** Last Solved At */
            last_solved_at?: string | null;
            /** Next Review Date */
            next_review_date?: string | null;
            /**
             * Is Mastered
             * @default false
             */
            is_mastered: boolean;
        };
        /**
         * ProblemSchema
         * @description Problem schema for list views.
         */
        ProblemSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Slug */
            slug: string;
            difficulty: components["schemas"]["Difficulty"];
            /** Pattern */
            pattern: string[];
            /** Sequence Number */
            sequence_number: number;
        };
        /**
         * ProblemWithProgressSchema
         * @description Problem with its user progress (nested structure for frontend).
         */
        ProblemWithProgressSchema: {
            problem: components["schemas"]["ProblemBasicSchema"];
            user_progress: components["schemas"]["UserProgressBasicSchema"] | null;
        };
        /**
         * ProgressResponse
         * @description Overview of user's progress across all Blind 75.
         */
        ProgressResponse: {
            /**
             * Problems
             * @description All problems with user progress
             */
            problems: components["schemas"]["ProblemWithProgressSchema"][];
            /**
             * Total Problems
             * @description Total problems in dataset (75)
             */
            total_problems: number;
            /**
             * Completed Problems
             * @description Problems solved at least once
             */
            completed_problems: number;
            /**
             * Mastered Problems
             * @description Problems mastered (solved 2x)
             */
            mastered_problems: number;
        };
        /**
         * RatingRequest
         * @description Request to rate a submission difficulty.
         */
        RatingRequest: {
            /**
             * Problem Slug
             * @description Problem slug identifier
             */
            problem_slug: string;
            /**
             * Rating
             * @description Difficulty rating: again, hard, good, or mastered
             */
            rating: string;
        };
        /**
         * RatingResponse
         * @description Response from rating a submission.
         */
        RatingResponse: {
            /**
             * Success
             * @description Whether rating was applied
             */
            success: boolean;
            /**
             * Interval Days
             * @description New interval in days until next review
             */
            interval_days: number;
            /**
             * Ease Factor
             * @description Updated ease factor
             */
            ease_factor: number;
            /**
             * Next Review Date
             * @description Next review date (ISO format)
             */
            next_review_date?: string | null;
            /**
             * Is Mastered
             * @description Whether problem is now mastered
             */
            is_mastered: boolean;
            /**
             * Review Count
             * @description Total number of reviews
             */
            review_count: number;
            /**
             * Times Solved
             * @description Total times solved
             */
            times_solved: number;
        };
        /**
         * ResetCodeRequest
         * @description Request body for resetting code.
         */
        ResetCodeRequest: {
            /** Problem Slug */
            problem_slug: string;
            /**
             * Language
             * @default python
             */
            language: string;
        };
        /**
         * ResetCodeResponse
         * @description Response for reset code endpoint.
         */
        ResetCodeResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message: string;
        };
        /**
         * RunCodeRequest
         * @description Request to run code against example test cases.
         */
        RunCodeRequest: {
            /**
             * Problem Slug
             * @description Problem slug identifier
             */
            problem_slug: string;
            /**
             * Code
             * @description User's code to execute
             */
            code: string;
            /** @description Programming language */
            language: components["schemas"]["Language"];
            /**
             * Custom Input
             * @description Custom test inputs (if provided, runs against these instead of DB test cases)
             */
            custom_input?: unknown[][] | null;
        };
        /**
         * RunCodeResponse
         * @description Response from running code.
         */
        RunCodeResponse: {
            /**
             * Success
             * @description Whether execution succeeded
             */
            success: boolean;
            /**
             * Results
             * @description Test case results
             */
            results: components["schemas"]["TestResult"][];
            /**
             * Summary
             * @description Summary stats (total, passed, failed)
             */
            summary: {
                [key: string]: unknown;
            };
            /**
             * Stdout
             * @description Raw stdout from Judge0
             */
            stdout?: string | null;
            /**
             * Stderr
             * @description Raw stderr from Judge0
             */
            stderr?: string | null;
            /**
             * Compile Error
             * @description Compilation errors if any
             */
            compile_error?: string | null;
            /**
             * Runtime Error
             * @description Runtime errors if any
             */
            runtime_error?: string | null;
        };
        /**
         * SaveCodeRequest
         * @description Request body for saving code.
         */
        SaveCodeRequest: {
            /** Problem Slug */
            problem_slug: string;
            /**
             * Language
             * @default python
             */
            language: string;
            /** Code */
            code: string;
        };
        /**
         * SaveCodeResponse
         * @description Response for save code endpoint.
         */
        SaveCodeResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message: string;
        };
        /**
         * SendMessageRequest
         * @description Request to send a message and stream AI response.
         */
        SendMessageRequest: {
            /**
             * Content
             * @description User message content
             */
            content: string;
            /**
             * Current Code
             * @description User's current code
             */
            current_code?: string | null;
            /**
             * Test Results
             * @description Test execution results
             */
            test_results?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * ShowAgainResponse
         * @description Response from marking a problem to show again.
         */
        ShowAgainResponse: {
            /**
             * Success
             * @description Whether the operation succeeded
             */
            success: boolean;
            /**
             * Message
             * @description Status message
             */
            message: string;
        };
        /**
         * SubmissionBasicSchema
         * @description Basic submission info for mastered problems.
         */
        SubmissionBasicSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Code */
            code: string;
            /** Language */
            language: string;
            /** Passed */
            passed: boolean;
            /** Runtime Ms */
            runtime_ms: number | null;
            /** Memory Kb */
            memory_kb: number | null;
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
        };
        /**
         * SubmissionSchema
         * @description Schema for submission history.
         */
        SubmissionSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Problem Id
             * Format: uuid
             */
            problem_id: string;
            /** Problem Title */
            problem_title: string;
            /** Code */
            code: string;
            /** Language */
            language: string;
            /** Passed */
            passed: boolean;
            /** Runtime Ms */
            runtime_ms: number | null;
            /** Memory Kb */
            memory_kb: number | null;
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
            /**
             * Total Test Cases
             * @default 0
             */
            total_test_cases: number;
            /**
             * Passed Count
             * @default 0
             */
            passed_count: number;
            /** Failed Test Number */
            failed_test_number?: number | null;
            /** Failed Input */
            failed_input?: {
                [key: string]: unknown;
            } | unknown[] | null;
            /** Failed Output */
            failed_output?: {
                [key: string]: unknown;
            } | unknown[] | number | string | boolean | null;
            /** Failed Expected */
            failed_expected?: {
                [key: string]: unknown;
            } | unknown[] | number | string | boolean | null;
        };
        /**
         * SubmitCodeRequest
         * @description Request to submit code (runs all test cases).
         */
        SubmitCodeRequest: {
            /**
             * Problem Slug
             * @description Problem slug identifier
             */
            problem_slug: string;
            /**
             * Code
             * @description User's code to execute
             */
            code: string;
            /** @description Programming language */
            language: components["schemas"]["Language"];
        };
        /**
         * SubmitCodeResponse
         * @description Response from code submission.
         */
        SubmitCodeResponse: {
            /**
             * Success
             * @description Whether all tests passed
             */
            success: boolean;
            /**
             * Results
             * @description All test results
             */
            results: components["schemas"]["TestResult"][];
            /**
             * Summary
             * @description Summary stats (total executed, passed, failed)
             */
            summary: {
                [key: string]: unknown;
            };
            /**
             * Total Test Cases
             * @description Total test cases in problem (for X/Y display)
             */
            total_test_cases: number;
            /**
             * Submission Id
             * @description Submission record ID
             */
            submission_id: string;
            /**
             * Runtime Ms
             * @description Execution time in milliseconds
             */
            runtime_ms?: number | null;
            /**
             * Memory Kb
             * @description Memory usage in kilobytes
             */
            memory_kb?: number | null;
            /**
             * Compile Error
             * @description Compilation errors if any
             */
            compile_error?: string | null;
            /**
             * Runtime Error
             * @description Runtime errors if any
             */
            runtime_error?: string | null;
            /**
             * Needs Rating
             * @description Whether user needs to rate difficulty
             * @default false
             */
            needs_rating: boolean;
            /**
             * Times Solved
             * @description Number of times solved
             */
            times_solved?: number | null;
            /**
             * Is Mastered
             * @description Whether problem is mastered
             */
            is_mastered?: boolean | null;
            /**
             * Next Review Date
             * @description Next review date (ISO format)
             */
            next_review_date?: string | null;
            /**
             * Interval Days
             * @description Current interval in days
             */
            interval_days?: number | null;
            /**
             * Ease Factor
             * @description Current ease factor
             */
            ease_factor?: number | null;
        };
        /**
         * TestCaseSchema
         * @description Test case schema (for responses).
         */
        TestCaseSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Input */
            input: {
                [key: string]: unknown;
            } | unknown[];
            /** Expected */
            expected: {
                [key: string]: unknown;
            } | unknown[] | number | string | boolean | null;
            /** Sequence */
            sequence: number;
        };
        /**
         * TestResult
         * @description Result from a single test case.
         */
        TestResult: {
            /** Test Number */
            test_number: number;
            /** Passed */
            passed: boolean;
            /** Input */
            input?: {
                [key: string]: unknown;
            } | unknown[] | string | number | boolean | null;
            /** Output */
            output?: {
                [key: string]: unknown;
            } | unknown[] | string | number | boolean | null;
            /** Expected */
            expected?: {
                [key: string]: unknown;
            } | unknown[] | string | number | boolean | null;
            /** Error */
            error?: string | null;
            /** Error Type */
            error_type?: string | null;
            /** Stdout */
            stdout?: string | null;
        };
        /**
         * TodaySessionResponse
         * @description Daily session response with up to 3 problems.
         *
         *     Includes 2 review problems (if due) + 1 new problem.
         */
        TodaySessionResponse: {
            /**
             * Review Problems
             * @description Problems due for review (max 2)
             */
            review_problems: components["schemas"]["ProblemProgressSchema"][];
            /** @description Next unsolved problem */
            new_problem?: components["schemas"]["ProblemProgressSchema"] | null;
            /**
             * Total Mastered
             * @description Total mastered problems
             */
            total_mastered: number;
            /**
             * Total Solved
             * @description Total problems solved at least once
             */
            total_solved: number;
        };
        /**
         * UpdateSessionRequest
         * @description Request to update a chat session.
         */
        UpdateSessionRequest: {
            /** Title */
            title?: string | null;
            mode?: components["schemas"]["ChatMode"] | null;
            /** Model */
            model?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /**
         * UserProgressBasicSchema
         * @description User progress info for progress list.
         */
        UserProgressBasicSchema: {
            /** Times Solved */
            times_solved: number;
            /** Last Solved At */
            last_solved_at: string | null;
            /** Next Review Date */
            next_review_date: string | null;
            /** Is Mastered */
            is_mastered: boolean;
            /** Show Again */
            show_again: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_problems_api_problems__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemSchema"][];
                };
            };
        };
    };
    get_problem_api_problems__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_languages_api_problems_languages_supported_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    run_code_api_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCodeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCodeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_code_api_submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitCodeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitCodeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rate_submission_api_rate_submission_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RatingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_today_api_today_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodaySessionResponse"];
                };
            };
        };
    };
    get_progress_api_progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressResponse"];
                };
            };
        };
    };
    get_mastered_api_mastered_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MasteredProblemsResponse"];
                };
            };
        };
    };
    show_again_api_mastered__problem_id__show_again_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                problem_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShowAgainResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_submissions_api_submissions__problem_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                problem_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionSchema"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_code_api_code_save_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveCodeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveCodeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_code_api_code_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetCodeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetCodeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    load_submission_code_api_code_load_submission_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoadSubmissionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveCodeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_api_chat_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelInfo"][];
                };
            };
        };
    };
    create_chat_session_api_chat_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSessionSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_chat_sessions__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSessionSchema"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chat_session_api_chat_session__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSessionWithMessagesSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_chat_session_api_chat_session__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_chat_session_api_chat_session__session_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSessionSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_stream_api_chat_session__session_id__message_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
